=== BasLee/textrepo/textrepo-app/src/test/resources/fields/fields.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/es-mapping.schema.json",
  "title": "Elasticsearch fields",
  "type": "object",
  "properties": {
    "id": {"type":"string", "enum": ["9"]},
    "text": {"type":"string"},
    "facsimiles": { "type":"array", "items": {"enum": [
      "https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0103.tif/info.json",
      "https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0104.tif/info.json",
      "https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0105.tif/info.json"
    ]}},
    "corr": {"type":"string", "enum": ["Gekaapte brieven"]},
    "date": {"type":"string", "enum": ["1672-05-15"]},
    "sender": {"type":"string", "enum": ["Jelte Pieters"]},
    "sendergender": {"type":"string", "enum": ["Vrouw"]},
    "recipient": {"type":"string", "enum": ["Andries Volkersen"]},
    "recipientgender": {"type":"string", "enum": ["Man"]},
    "recipientship": {"type":"string", "enum": ["Zoetendaal"]},
    "texttypes": {"type":"array", "items": { "enum": ["Onbekend"]}},
    "languages": {"type":"array", "items": { "enum": ["Duits"]}},
    "has_date": {"type":"boolean", "enum": [true]},
    "sender_or_recipient": {"type":"array", "items": { "enum": ["Jelte Pieters", "Andries Volkersen"]}},
    "person": {"type":"array", "items": { "enum": ["Augusto & Caesare"]}},
    "org": {"type":"array", "items": { "enum": ["Regnante Invictissimo Romanorum Imperatore ac"]}},
    "loc": {"type":"array", "items": { "enum": ["Dreijfaltigkeitt  Amen\n  Anno Christi"]}},
    "misc": {"type":"array", "items": { "enum": ["Indi-"]}}
  },
  "required": ["id","text","facsimiles","corr","date","sender","sendergender","recipient","recipientgender","recipientship","texttypes","languages","has_date","sender_or_recipient","person","org","loc","misc"
  ]
}

=== BasLee/textrepo/nginx/custom-index/fields.json
{"id":"9","text":"1672Im Nahmen der Heijligen Dreijfaltigkeitt  Amen\n  Anno Christi Ein tausendt, sechßhundert, zweij undt siebenzig, Indi-\n  ctione decimâ, Regnante Invictissimo Romanorum Imperatore ac\n  Domino, Domino LEOPOLDO, semper Augusto & Caesare ac Domino\n  nostro clementissimo, Imperii Maj[esta]tis, Suae Caesarea anno decimo quarto,\n  Mittwochenß, den fünffzehnden Maij st(ilo) vet. Mittageß, umb zwolff\n  Uhren, sind vor mir Chrostophoro Greven, Kaijserl(ichen) Offenbahren, geschwor-\n  nen, und am hochpreißlichen Kaijserl(ichen) Cammergericht approbirten und Imma-\n  triculirten Notario und Bürgern dieser Stadt Hamb(urg) alhir in Hamburg, in\n  meinem an der Börse belegenen Schreib Conthoir persöhnlich erschienen die\n  Ehrenveste und fürnehme S(eigneu)res Arnold Beltgens und Philip Verpoorten\n  wollbenambte Kauffleute alhir, Befrachtere an einem: undt der\n  Erbare Peter Tamm, Bürger hieselbsten, undt Schiffer negst Gott von dreij\n  Schiffe, genandt die Stadt Hamburg, groß ungefehr Einhundert undt vier-\n  zich Lasten, gemontiret mit zwantzig Stücken Geschütz, anderßtheils, an-\n  zeigende und öffentlich bekennende, mit einander eine Befrachtung deß\n  itzt  gemelten Schiffes gecontractiret und geschloßen zu haben, inmaßen\n  sie auch Krafft dieseß contractiren undt schließen wie folget:\n  Erstlich verplichtet sich der Schiffer Vorgedachtes sein neie Schiff mit dem\n  ersten Siegell fertig zu machen, auch woll zu dichten und zu fleijen von un-\n  ten und oben, auch woll undt gebührlich zu versehen mit Masten, Siegelß, Ankers\n  Lawen[?], Cabelß, Victualien, Munition, Schiffs- Volcke undt aller andern Zu-\n  behoör, alß zu nachbeschriebenen Reise behöret und von nöthen ist, damit er\n  mit die anderen auff Rußlandt von seinen befrachtete Schiffe, uff bevor-\n  stehende Reise unverzüglich könne abgehen. ----- Undt geloben die\n  Befrachtere Ihn den Schiffer biß medio Junij ohnfehlbarlich abzuladen\n  mit sothanigen Wahren undt Kauffmanschaften, alß ihnen beliebet. Wor-\n  mit er der Schiffer alßdan mit guten Wetter undt  Winde von hinnen soll\n  absiegeln nach Archangel in Rußlandt, undt nach geliebtß Gott glück-\n  licher Ankunfft alda mit seinem Schiffe zu Dienste der Befrachtere lie-\n  gen biß den achtzehenden Septembris, umb mitler Zeit alda geloßet\n  undt wieder geladen zu werden durch die Befrachtere oder Commiss, oder\n  durch andere zu ihrem Profite. Die ubrigen Liggetage nach den 18. Septembris\n  sollen die Befrachtere vor jeden Liggetag zu bezahlen schüldig sein fünff\n  undt zwantzig Reichßthaler, doch soll der Schiffer nicht mehr alß zehen\n  Tage verobligiret sein zu warten, sondern alßdan Macht haben zu siegeln,\n  undt ledig vor voll bezahlet werden:   undt soll der Schiffer nicht  bemech-\n  tiget sein von jemandt anderß ohne daß Commiss wißen und willen einige\n  Güter darin zuladen beij willkührlicher Pöen[Strafe] Eintausendt Reichßthaler,\n  jedoch vorbeheltlich dem Schiffer undt seinem Volcke vier Lasten ins Raumb\n  zur Führung vor sich selbsten, undt vor niemandt anderß zu laden; Eß\n  sollen auch keine Kauffmansgütere uff dem Uberlauff geführet wer-\n  den, sondern die Ladung soll geschehen inß Raumb von dem Schiffe mit\n  Gütern oder Wahren nach der Kauffleute Belieben, jedoch nicht über\n  zwolff  Lasten schwincken, undt darunter so viell schwer Gutt;  Jüfften vor\n  schwer Gutt gerechnet, daß das Schiff  waßersteiff genug seij, umb be-\n  quemblich über die See zu gehen, doch solte eß damit nicht steiff ge-\n  nug sein, sollen die Befrachtere schüldig sein Steine zu verschaffen undtzu bezahlen, aber keine Fracht dafür geben, auch mit accomodation etlicher\n  halben Packen zur bequemblichen Stowung dem Schiffer favorisiren.  Undt\n  werden folgender Gestalt die Lasten gerechnet, nemblich jede Last\n  120.  Pude oder 4000. lb. [Pfund] Lollich, Wachß undt Caviar brutto.\n  3.  Packen Jüfften  jeder von 66.  Paren\n  150.  Astracanische  Heute.  [Häute]\n  200. Schwincken, nemblich zweij Packen, jede von 100. Stücken, oder da-\n  ferner der Schiffer sie loß begehrt  220.  p(e)r Last.\n  14. Tonnen  Salm  und andere schmale Tonnen.\n  8.  Rußische  ordinari  Uxhaubter.\n  Undt alleß andere alß gebreuchlich ist.\n  Zu Archangel  soll die Ladung geschehen binnen oder außerhalb der Baar\n  oder hinter daß Sameijeten Eijlandt, nach der Befrachter oder Commiss\n  Belieben, undt alda zu Archangel soviell Lasten eingenommen werden, dar-\n  mit daß Schiff bequemlich über die Baar, oder hinter daß Eijlandt umbkom-\n  men kan.  Der Schiffer ist verbunden vor seinem Verreisen die Cognosce-\n  menten von seinen einhabenden Gütern zu zeichnen, auch durch sein Schiffs-\n  Volck alß gebreuchlich, mit dem Schiffs bote und anderer Commodität die\n  Gütere an- und von dem Lande ab- und an Schiffsbohrt führen undt brin-\n  gen zu laßen, dieselbe zu loßen undt laden,  so offtmahlß  solcheß die Not-\n  turfft erfo(r)dert und die Commissen begehren werden;  Undt soll der Schiffer\n  verbunden sein, wan er 130.  Lasten eingeladen hat, den Befrachteren\n  oder Commiss zu sagen, wie viell Lasten er noch laden kan, waß er alß-\n  dan mehr fo(r)dert, und nicht ladet, soll Er  für jede Last fünffzig Reichßth(ale)r\n  Pöen zu bezahlen schüldig sein, auch in zeit der Noth und Brandt, so Gott\n  gnedig verhüte, alle mögliche Hülffe zu thunde, umb der Befrachter Gü-\n  ter zu  salviren. --Undt gelobet der Schiffer im stawende und abladende,\n  auch sonsten guter Auffsicht der Befrachter Bestes nach allen Vermügen zu\n  wißen und zu befederen;  auch sobald er geladen ist, mit guten Wetter\n  undt Winde ohnverzuglich abzusiegeln recht zu nach Livorno, und Müyn\n  Scalieren, wor eß  der Schiffer und seine Haubt- Officizers vor gutt befin-\n  den,  undt nach geliebtß Gott glücklichem arriviment daselbst seine einha-\n  bende Ladung zu lieffern an der befrachtere Commissen, vermüge der Cogno-\n  scementen, welche gehalten sein sollen von dato deß  arriviments, innerhalb\n  den negsten dreijen Wochen, lauffenden Werckelltagen,  Ihn zu laßen,\n  undt nach gethaner behörlichen  guten Liefferung Ihme ohnverzuglich zu\n  bezahlen zu Fracht vor solcher gantzen Reise in allem fünffzig Stück von\n  achten, in platte doble, Seuillanse und Mexicanse Stück von 8. tens vor jede\n  obengespecificirte vermüge der Cognoscementen zu Archangel einge-\n  nommene Rußische Last, biß zur vollen Ladung, geladen oder unge-\n  laden wesende, beneben ein halb Stück von achten avaria ordinaria,\n  und ein halb Stück von achten vor dem Schiffer zum Kapplaken p(e)r Last,\n  sambt einer newen Flaggen Vorß. Schiff alhier. ---Undt ist zur Arch-\n  angel daß Schiff nach Costumbe  von Pilotage undt anquerage in undt\n  auß freij, sonsten aber soll eß mit der andern Pilotage undt avaria\n  gehalten werden nach Usance, und costumbe von der See.  Waß auchder Schiffer zu livorno durch die Commissen mit der Loßung lenger\n  alß dreij Wochen werckelltage uffgehalten wird, soll er vor jeg-\n  lichen  Werckelltag gleichfalß fünff undt zwantzig Reichsthler\n  zugewiesen und zu empfangen haben.  Eß ist aber außtrücklich\n  auch dabeij verabredet, daß der Schiffer in der Hinreise hinter daß\n  Eijlandt  Caldin zu scalieren soll schüldig sein, undt alda einnehmen,\n  waß alda für die Befrachtere oder Commiss zu laden solt.\n  Undt dieseß alleß also gebührlich zu vollbringen, verbinden die Con-\n  trahenten respective ihre Persohnen, Habe und Güter, in specie die\n  Befrachtere ihre Ladung, undt der Schiffer sein Schiff, Fracht undt al-\n  le Gerechtschaffen deßelbigen,  Solcheß alleß submittirende untern\n  Bezwang und paraten Execution aller Rechten und Gerichten, renun-\n  ciirende alle und jeden Exceptionen außtrücklich undt Begnadungen\n  geist- und weltlichen Gerichteß und Rechtens, auch der reget  sagen=\n  de;  daß die gemeine Verzicht nicht gültig seij;  wo nicht die sonder-\n  bahre außtrücklichen Verhergehe.  Ohne List undt Gefehrde.\n  In  Uhrkundt  der Wahrheit undt steter Festerhaltung alleß  deßen\n  so obsteht, haben beiderseitß Contrahenten diese Certeparteij  in\n  meinem haltenden Notariat- protocoll  eigenhendig unterschrieben,\n  und mich Notarium  gebeten   ihnen darauß  dieß  zzdocumentum in con-\n  sneta  forma darüber zu ertheilen.  Actum hamburg  ut  supra   p.\n\n  Ist  unterzeichnet\n\n  Arnoldt   Bettgens                                E  Philip  verpoorten\n  Inv:\n  ==   Pieter Tamm:\n\n  [zegel /Petschaft  rund  mit\n  Lorbeerkranz auf Empore:\n  1654    FACIES  ANNO   SI  RECTE ]\n\n  In majorem a fidem ac testimonium omnium Dimissorum de super\n  Instrumentum  hocce  confeci,  scripsi , subscripsi,  &  consueto No-\n  tariatús  publico  signo,  &  privato  sigillo  communivi.  Ad  hac\n  oia  legitime  &  debito  modo  pro officii fide requisitus  &  rogatus\n\n  Christophorus            Greve\n  Sacr. a  Imp.i  Auth.  Publ.  &  in Aug.a  Rom.  Impii\n  Cam.a  Immatric. tus  Notar  &  Civ.  Hamb.\n\n  =================  #  ==============","facsimiles":["https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0103.tif/info.json","https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0104.tif/info.json","https://images.huygens.knaw.nl/iiif/hca30-223/1/nl-hana_hca30-223_1_0105.tif/info.json"],"corr":"Gekaapte brieven","date":"1672-05-15","sender":"Jelte Pieters","sendergender":"Vrouw","recipient":"Andries Volkersen","recipientgender":"Man","recipientship":"Zoetendaal","texttypes":["Onbekend"],"languages":["Duits"],"has_date":true,"sender_or_recipient":["Jelte Pieters","Andries Volkersen"],"person":["Augusto & Caesare"],"org":["Regnante Invictissimo Romanorum Imperatore ac"],"loc":["Dreijfaltigkeitt  Amen\n  Anno Christi"],"misc":["Indi-"]}
